### ISSUE TITLE
Package wchttpserver_rest doesn't compile on Lazarus 3.4 fpc 3.2.2 - Windows 10 64bit 

### ISSUE THREAD

**Issue by Arguilar** [iLya2IK/wchttpserver#9]
Package wchttpserver_rest doesn't compile on Lazarus 3.4 fpc 3.2.2, OS WIN10-64BIT.
When trying to compile this package Lazurus raise "wcnetworking.pas(1655,38) Error: Identifier not found "ssCanRead". The same for "ssCanSend", "ssError".
How do you think I could solve this?

**Comment by iLya2IK** [comment]
Changes have been made to fix compilation errors in socket_select mode (Windows)
